feat: 1Sprint 1 сделать ветку controllers-films-users
antbaranov/java-filmorate pull request #1
Opened 2022-10-27 17:14 UTC by antbaranov

2022-10-27 17:21 UTC, antbaranov commented
feat: сделать ветку controllers-films-users

2022-10-28 13:03 UTC, AnastasiyaFomkina requested changes

2022-10-28 13:03 UTC, afomkina commented on pom.xml
> +	<description>Бэкенд для сервиса, который будет работать с фильмами и оценками пользователей, а также возвращать топ-5 фильмов, рекомендованных к просмотру.</description>
👍

2022-10-28 13:03 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +      private final Map<Integer, Film> films = new HashMap();
Не хватает `<>` после `HashMap`
```suggestion
      private final Map<Integer, Film> films = new HashMap<>();
```
+ лишний пробел, поправь, пожалуйста, класс по code-style: [Ctrl+Alt+L](https://blog.jetbrains.com/idea/2020/03/top-15-intellij-idea-shortcuts/#:~:text=next%20need%20it.-,%E2%8C%A5%E2%8C%98L%20or%20Ctrl%2BAlt%2BL,-We%20can%20easily)

2022-10-28 13:03 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            log.warn("Дата выпуска фильма: {} /n Продолжительность фильма: {}", film.getReleaseDate(), film.getDuration());
Поправь, пожалуйста, символ переноса строки с `/n` на `\n`. Это можно сделать быстро по всему проекту с помощью сочетания клавиш Ctrl+Shift+R: https://disk.yandex.ru/d/V5-PHZIJeWOLhw

2022-10-28 13:03 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Фильм: {} успешно добавлен в коллекцию", film.getName());
Логи - это круто, молодец 🔥

2022-10-28 13:03 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        Collection<Film> filmCollection = films.values();
_Опционально_
В коммерческой разработке уже дано никто не пишет обычные циклы, так как в java 8 появился потрясный [stream api](https://javarush.ru/groups/posts/2203-stream-api)
Предлагаю попробовать написать через [stream.filter](https://vertex-academy.com/tutorials/ru/java-8-stream-filter/) c терминатольй оперецией [findAny()](https://vertex-academy.com/tutorials/ru/java-8-stream-find/) или [stream.anyMatch](https://vertex-academy.com/tutorials/ru/java-8-stream-match/)

2022-10-28 13:03 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        for (Film flm : filmCollection) {
Лучше называть переменные более осмысленно, так проще понимать, что происходит в коде.
Например, здесь подойдет: `filmFromCollection` или что-то в этом духе. А лучше заменить наименование параметра метода на (прим. `filmToAdd`), а здесь оставить `film`

2022-10-28 13:03 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            if (film.getName().equals(flm.getName()) && film.getReleaseDate().equals(flm.getReleaseDate())) {
Сложную логику проверки лучше выносить в отдельный метод
Прим. `private boolean isAlreadyExist(Film film, Film filmToAdd)`
Так сложночитаемая проверка :
`if (film.getName().equals(flm.getName()) && film.getReleaseDate().equals(flm.getReleaseDate()))`
превратиться в 
` if (isAlreadyExist(flm, film)) `

2022-10-28 13:03 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getName() == null || user.getName().isBlank()) user.setName(user.getLogin());
Во все, даже однострочные ветвления, в коммерческой разработке принято добавлять `{}` - так код выглядит структурнее и его проще читать

2022-10-28 13:03 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        for (User usr : userCollection) {
_Опционально_
Предлагаю тоже попробовать написать через `stream api`

2022-10-28 13:03 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +class FilmorateApplicationTests {
🔥

2022-10-28 13:13 UTC, antbaranov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +      private final Map<Integer, Film> films = new HashMap();
Тогда почему тесты пропустили эту ошибку?

2022-10-28 13:38 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +      private final Map<Integer, Film> films = new HashMap();
Это не ошибка, можно оставить без `<>`. Просто мы лишимся дополнительной проверки на нужный тип. Когда мы добавляем тут `<>` - компилятор автоматически проверяет, что в качестве ключа у нас должен быть только объект класса `Integer`, а в качестве значения  - `Film`, просто для сокращения кода дублирование параметров опускается и остается только `<>`

2022-10-28 14:20 UTC, antbaranov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +      private final Map<Integer, Film> films = new HashMap();
Понятно

_Сообщения доставляются моментально из этой ветки, без каких-либо дополнительных манипуляций? Как чат/ мессенджер?_

2022-10-28 15:26 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +      private final Map<Integer, Film> films = new HashMap();
Мне приходит отбивка на почту, что сделано изменение :)

Но все же в качестве мессенджера лучше использовать слак. А комментарии к pr - для подсвечивания каких-либо моментов в коде

2022-10-28 15:58 UTC, antbaranov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        Collection<Film> filmCollection = films.values();
Я все усложнил. а не упростил

`private void check2(@RequestBody Film filmToAdd) {
        Collection<Film> filmFromCollection = films.values();
        Optional<Film> filmAlreadyExist = filmFromCollection.stream()
                .filter(film -> film.equals(filmToAdd.getName()))
                .filter(film -> film.equals(filmToAdd.getReleaseDate()))
                .findAny();
        if (filmFromCollection.stream()
                .filter(film -> film.equals(filmToAdd.getName()))
                .filter(film -> film.equals(filmToAdd.getReleaseDate()))
                .anyMatch()) {
            log.warn("Фильм к добавлению: {}\nФильм имеется в коллекции: {}", filmToAdd, filmAlreadyExist);
            throw new ValidationException("Такой фильм уже существует в коллекции");
        } 
    }`

2022-10-28 16:33 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        Collection<Film> filmCollection = films.values();
Немножечко смешал все в одно :)
Тут два решения :
 1) через  filter + findAny
 2) через  anyMatch
 
Проще сначала попробовать через ` .anyMatch()` - после него ненужны никакие терминальные операции, так как он сразу возвращает  boolean:

Логика такая должна быть такая:
boolean exists = коллекция -> создаем стрим -> anyMatch(здесь должна быть лямба с проверкой ```
filmToAdd.getName().equals(film.getName()) &&
                filmToAdd.getReleaseDate().equals(film.getReleaseDate()
```)
а дальше проверка, что если exists == true -> бросаем ошибку ValidationException

Более сложный вариант через filter выглядит так:
коллекция -> создаем стрим -> filter(здесь должна быть лямба с проверкой что, ```
!filmToAdd.getName().equals(film.getName()) &&
                !filmToAdd.getReleaseDate().equals(film.getReleaseDate()
```) -> findAny() -> так как findAny() возвращает [Optional](https://habr.com/ru/post/346782/), надо его корректно достать, здесь нам отлично подходит `.orElseThrow()`, так как нам надо выкинуть ошибку
Более схематично:
коллекция. стрим()
     .filter(проверка)
     .findAny()
     .orElseThrow(ошибка)

2022-10-28 16:37 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        Collection<Film> filmCollection = films.values();
Предлагаю еще раз попробовать, если совсем не понятно - не страшно. Дальше обязательно станет проще 😉

2022-10-28 16:38 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        Collection<Film> filmCollection = films.values();
в лямбде с проверкой можно использовать новый метод isAlreadyExist, тогда код будет выглядеть гораздо проще

2022-10-28 16:47 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (filmFromCollection.stream().anyMatch(film -> film.getName().equals(filmToAdd.getName()) &&
Предлагаю проверку вынести в отдельный метод isAlreadyExists, а сам стрим вынести в отдельную переменную. 
Тогда код будет выглядеть проще:
boolean exists  = stream.anyMatch(film->isAlreadyExists(film, filmToAdd)
if(exists){выкинуть ошибку}

В коммерческой разработке принято начинать каждую операцию стрима с новой строки, так как стрим так проще читать:
```
films.values().stream()
   .someMoreOperation()
   .someMoreOperation()
   .anyMatch()              
```

2022-10-28 16:47 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (userFromCollection.stream().anyMatch(user -> user.getLogin().equals(userToAdd.getLogin())
И здесь тоже

2022-10-28 18:51 UTC, antbaranov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        Collection<Film> filmCollection = films.values();
Да, я хотел спросить о надобности для стрима созданного метода isAlreadyExist() для цикла, но постеснялся показаться ... А оказалось, что я правильно думал

2022-10-29 13:18 UTC, AnastasiyaFomkina approved these changes
Клево получилось, молодец 👍

2022-11-05 11:01 UTC, antbaranov commented
Созданы тесты

2022-11-11 14:55 UTC, merged