Add database
antbaranov/java-filmorate pull request #6
Opened 2022-12-07 08:13 UTC by antbaranov

2022-12-08 16:03 UTC, AnastasiyaFomkina requested changes
Нужно добавить игнорирование файлов `.DS_Store` в `.gitignore` и удалить их - они не нужны в репозитории

2022-12-08 16:03 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        log.info("400 {}", e.getMessage(), e);
Нужно переименовать все однобуквенные переменные, они делают код менее читаемым

2022-12-08 16:03 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        log.info("404 {}", e.getMessage(), e);
Второй параметр `e` не будет отражен в логах, лучше его удалить, так как мы и так печатаем сообщение исключения

2022-12-08 16:03 UTC, afomkina commented on src/test/java/ru/yandex/practicum/filmorate/storage/FilmStorageTest.java
> +class FilmStorageTest {
Лучше добавить еще два теста для `GenreStorage` и `MpaStorage`

2022-12-08 16:03 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +
Лишний отступ, лучше удалить

2022-12-08 16:03 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @Autowired(required = false)
Можно инжектить поля через [@RequiredArgsConstructor](https://javabydeveloper.com/lombok-requiredargsconstructor-examples/) от lombok - это поможет сократить код, чтобы не писать одинаковые скучные конструкторы 😉

2022-12-08 16:03 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +@AllArgsConstructor
Лучше оставить `@RequiredArgsConstructor`, чтобы инжектить только конкретные нужные нам поля, а не все, которые есть в классе

2022-12-08 16:03 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +
Лишний отступ

2022-12-08 16:03 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +@Data
Лучше вернуть `@Getter` и `@Setter`, так как у нас уже есть нужные конструкторы и методы `equals` и `hashCode`, которые также генерируются с помощью аннотации `@Data`.
Вот отличная [статья](https://habr.com/ru/company/piter/blog/676394/) про аннотации lombok

2022-12-08 16:03 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +        if (!(o instanceof Film)) return false;
В коммерческой разработке принято добавлять `{}` даже в однострочные конструкции if. Так код становится более структурированным и его проще читать

2022-12-08 16:03 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +import lombok.*;
_Саморазвитие_
В коммерческой разработке не принято использовать `wildcard` в импортах.
Вот отличная [статья](https://struchkov.dev/blog/using-wildcard-imports-in-java/) почему и как настроить идею, чтобы избавиться от `*`
Кстати, в IDEA есть отличное сочетание клавиш `Ctrl + Alt + O` - при нажатии сочетания в нужном классе автоматически оптимизируются импорты и удаляются ненужные

2022-12-08 16:03 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        log.info("Фильм с id: '" + id + "' отправлен");
Лучше использовать [String.format](https://javarush.com/quests/lectures/questmultithreading.level02.lecture06), если нужно добавить какой-либо параметр в строку. Так код становится проще читать

2022-12-08 16:03 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        return null;
Нужно удалить все неиспользуемые методы

2022-12-08 16:03 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +            PreparedStatement stmt = connection.prepareStatement(sqlQuery, Statement.RETURN_GENERATED_KEYS);
В java переменные принято именовать "осмысленно", переименуй, пожалуйста, сокращения

2022-12-08 16:03 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/storage/FilmStorageTest.java
> +    private Film film = new Film(1,
Все тестовые объект `Film` нужно сделать `final`, чтобы обезопасить от внезапного изменения

2022-12-08 16:03 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/storage/UserStorageTest.java
> +    private User user3 = new User(3,
Все тестовые объект `User` нужно сделать `final`, чтобы обезопасить от внезапного изменения

2022-12-08 18:04 UTC, antbaranov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        log.info("404 {}", e.getMessage(), e);
public ErrorResponse handlerInternalException(final InternalException e) {
        log.info("500 {}", e.getMessage());
        return new ErrorResponse(e.getMessage(), e ); // вторая e  - так на вэбинаре говорили
    }

2022-12-09 14:42 UTC, AnastasiyaFomkina approved these changes
Отлично 👍

2022-12-09 14:42 UTC, AnastasiyaFomkina commented on .gitignore
> +.DS_Store
👍

2022-12-09 14:42 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        log.info("404 {}", e.getMessage(), e);
Да, все верно, но тут `new ErrorResponse(e.getMessage(), e )` ты создаешь объект ErrorResponse с полями `e.getMessage()` и `e`
А я говорю про логирование: `log.info("404 {}", e.getMessage(), e);`. В данном случае в логе у тебя одно окошко для параметра `{}`, поэтому второй параметр `e` логироваться не будет

2022-12-09 18:23 UTC, antbaranov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +        log.info("404 {}", e.getMessage(), e);
log.info("404 {} {}", e.getMessage(), e);

2022-12-19 10:16 UTC, merged